name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution
        run: msbuild WebSocketDLL.sln /p:Configuration=Release

      - name: Upload WebSocketDLL Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: WebSocketDLL
          path: ./Release/WebSocketDLL.dll
