name: Build WebSocket DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build DLL
        run: |
          MSBuild.exe WebSocketDLL.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload DLL
        uses: actions/upload-artifact@v3
        with:
          name: WebSocketDLL
          path: Release/WebSocketDLL.dll
